### ISSUE TITLE
Device not supported: Galaxy S4 Mini LTE

### ISSUE THREAD

**Issue by shrmnk** [cesco89/android-kernel-tweaker#1]
Hi, 

I was previously able to download and use this app but after a recent clean reflash of the latest CM 11 nightly with f4ktion kernel, the Play Store no longer allows me to download the app. 

Model: GT-I9195

**Comment by hungmom78** [comment]
Hay

**Comment by cesco89** [comment]
Hi :)
Check Google+ and try the new version : https://drive.google.com/file/d/0BxhXoOizKZSkTDN6T0hPOUYtMHc/edit?usp=sharing

To use this one you have to uninstall the old version (if any) ;)

The app will be pushed to Google Play when ready :)

For any report, please check the new project here on github: https://github.com/cesco89/android_kernel_tweaker_2
